title: Tomas Hodan
logo: /assets/img/Tomas_Hodan_2022_square.jpg
description: Research Scientist at <a href="https://tech.facebook.com/reality-labs/">Meta</a>
theme: jekyll-theme-minimal

email: "&#116;&#111;&#109;&#46;&#104;&#111;&#100;&#97;&#110;&#64;&#103;&#109;&#97;&#105;&#108;&#46;&#99;&#111;&#109;"
google_scholar_link: https://scholar.google.com/citations?user=GD_VE9oAAAAJ&hl=en
cv_link: /assets/data/Hodan_CV.pdf
github_link: https://github.com/thodan
linkedin_link: http://linkedin.com/in/tomashodan
twitter_link: https://twitter.com/tomhodan
